platform :ios, '10.0'

target 'PocketCRM for Vtiger' do
	use_frameworks!
	pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
	pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
	pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
		'Core',
    		'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    		'RCTText',
		'RCTImage',
    		'RCTNetwork',
		'RCTAnimation',
		'CxxBridge',
		'RCTLinkingIOS',
    		'RCTWebSocket', # needed for debugging
  	]
	pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  post_install do |installer|
	react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
	react_project.main_group["React/Views"].files.each do |file|
	  if file.path.match(/^RCTWebView/)
		file.remove_from_project
	  end
	end
	react_project.save
  end
  
end
